version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: marketplace
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U app -d marketplace"]
      interval: 5s
      timeout: 3s
      retries: 20

  catalog:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/marketplace
      SPRING_DATASOURCE_USERNAME: app
      SPRING_DATASOURCE_PASSWORD: app
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports: ["8080:8080"]
    depends_on:
      postgres:
        condition: service_healthy
