spring:
  profiles:
    active: dev

---

# ========== DEV PROFILE ==========
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:pipeline;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      "[hibernate.dialect]": org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# External service URLs
services:
  catalog-service:
    url: http://localhost:8081
  runner-service:
    url: http://localhost:8080

---

# ========== LOCAL POSTGRES PROFILE ==========
spring:
  config:
    activate:
      on-profile: local-postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/marketplace
    username: app
    password: app
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      "[hibernate.dialect]": org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# External service URLs
services:
  catalog-service:
    url: ${CATALOG_SERVICE_URL:http://localhost:8081}
  runner-service:
    url: ${RUNNER_SERVICE_URL:http://localhost:8080}